// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var phonecatApp;

  phonecatApp = angular.module('phonecatApp', ['ngRoute', 'phonecatControllers', 'phonecatFilter']);

  phonecatApp.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/phones', {
        templateUrl: 'partials/phone-list.html',
        controller: 'PhoneListCtrl'
      }).when('/phones/:phoneId', {
        templateUrl: 'partials/phone-detail.html',
        controller: 'PhoneDetailCtrl'
      }).otherwise({
        redirectTo: '/phones'
      });
    }
  ]);

}).call(this);
