// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var phonecatApp;

  phonecatApp = angular.module('phonecatApp', []);

  phonecatApp.controller('PhoneListCtrl', function($scope, $http) {
    $http.get('phones/phones.json').success(function(data) {
      return $scope.phones = data;
    });
    return $scope.orderProp = 'age';
  });

}).call(this);
