// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var phonecatControllers;

  phonecatControllers = angular.module('phonecatControllers', []);

  phonecatControllers.controller('PhoneListCtrl', [
    '$scope', '$http', function($scope, $http) {
      $http.get('phones/phones.json').success(function(data) {
        return $scope.phones = data;
      });
      return $scope.orderProp = 'age';
    }
  ]);

  phonecatControllers.controller('PhoneDetailCtrl', [
    '$scope', '$http', '$routeParams', function($scope, $http, $routeParams) {
      $http.get("phones/" + $routeParams.phoneId + ".json").success(function(data) {
        $scope.phone = data;
        return $scope.mainImageUrl = data.images[0];
      });
      return $scope.setImage = function(imageUrl) {
        return $scope.mainImageUrl = imageUrl;
      };
    }
  ]);

}).call(this);
