// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var phonecatFilters;

  phonecatFilters = angular.module('phonecatFilters', []);

  phonecatFilters.filter('checkmark', function() {
    return function(input) {
      if (input) {
        return '\u2713';
      } else {
        return '\u2718';
      }
    };
  });

}).call(this);
