// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var phonecatServices;

  phonecatServices = angular.module('phonecatServices', ['ngResource']);

  phonecatServices.factory('Phone', [
    '$resource', function($resource) {
      return $resource('phones/:phoneId.json', {}, {
        query: {
          method: 'GET',
          params: {
            phoneId: 'phones'
          },
          isArray: true
        }
      });
    }
  ]);

}).call(this);
