// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  describe('PhoneCat controllers', function() {
    return describe('PhoneListCtrl', function() {
      var ctrl, scope;
      beforeEach(module('phonecatApp'));
      scope = null;
      ctrl = null;
      beforeEach(inject(function($controller) {
        scope = {};
        return ctrl = $controller('PhoneListCtrl', {
          $scope: scope
        });
      }));
      it('should create "phones" model with 3 phones', function() {
        return expect(scope.phones.length).toBe(3);
      });
      return it('should set the default value of orderProp model as "age"', function() {
        return expect(scope.phones.length).toBe(3);
      });
    });
  });

}).call(this);
