// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  describe('PhoneCat App', function() {
    it('should redirect');
    return describe('Phone list view', function() {
      beforeEach(function() {
        return browser.get('app/index.html');
      });
      it('should filter the phone list as a user types into the search box', function() {
        var phoneList, query;
        phoneList = element.all(By.repeater('phone in phones'));
        query = element(By.model('query'));
        expect(phoneList.count()).toBe(3);
        query.sendKeys('nexus');
        expect(phoneList.count()).toBe(1);
        query.clear();
        query.sendKeys('motorola');
        return expect(phoneList.count()).toBe(2);
      });
      return it('should be possible to controle the order of phones via select box', function() {});
    });
  });

}).call(this);
